Support several initramfs-specifications
Allow multiple lines "initramfs ... followkernel" in /boot/config.txt
and update only lines matching the current kernel version suffix (such
as "-v7l").

Also disable the "screen" shortcut for locking the screen. This can be
deadly if no password has been set for the user, because (s)he will
never be able to unlock the terminal again without reattaching from a
different terminal.

If a user actually wants to lock the "screen" terminal, (s)he can always
enter the command at the colon prompt of "screen".

diff --git a/initramfs-tools/hooks/update_initrd_ref_qaumv1g34z54324pbel831evd b/initramfs-tools/hooks/update_initrd_ref_qaumv1g34z54324pbel831evd
--- a/initramfs-tools/hooks/update_initrd_ref_qaumv1g34z54324pbel831evd
+++ b/initramfs-tools/hooks/update_initrd_ref_qaumv1g34z54324pbel831evd
@@ -1,25 +1,46 @@
-#! /bin/sh -e
+#! /bin/sh
+
+# v2023.142
+#
 # Update reference to $INITRD in $BOOTCFG, making the kernel use the new
-# initrd after the next reboot.
+# initrd after the next reboot. The target version is taken from $version.
 BOOTLDR_DIR=/boot
 BOOTCFG=$BOOTLDR_DIR/config.txt
-INITRD_PFX=initrd.img-
-INITRD=$INITRD_PFX$version
 
 case $1 in
 	prereqs) echo; exit
 esac
 
-FROM="^ *\\(initramfs\\) \\+$INITRD_PFX.\\+ \\+\\(followkernel\\) *\$"
-INTO="\\1 $INITRD \\2"
+set -e
+cleanup() {
+	rc=$?
+	test "$T" && rm -- "$T"
+	test $rc = 0 || echo "\"$0\" failed!" >& 2
+}
+T=
+trap cleanup 0
+trap 'exit $?' INT QUIT TERM HUP
 
-T=`umask 077 && mktemp --tmpdir genramfs_XXXXXXXXXX.tmp`
-trap "rm -- \"$T\"" 0
+test "$version"
+npfx=`expr x"$version" : x'\(\([1-9][0-9]*\.\)*[1-9][0-9]*\)'`
+nsfx=${version#"$npfx"}
+T=`mktemp -- ${TMPDIR:-/tmp}/${0##*/}.XXXXXXXXXX`
 
-sed "s/$FROM/$INTO/" "$BOOTCFG" > "$T"
+orx=' *initramfs \{1,\}initrd\.img-\([-.0-9a-z]\{1,\}+\) \{1,\}'`:
+	`'followkernel *$'
+while IFS= read -r line
+do
+	ov=`expr x"$line" : x"$orx"` \
+	&& test "$ov" \
+	&& opfx=`expr x"$ov" : x'\(\([1-9][0-9]*\.\)*[1-9][0-9]*\)'` \
+	&& osfx=${ov#"$opfx"} \
+	&& test "$nsfx" = "$osfx" \
+	&& echo "initramfs initrd.img-$npfx$osfx followkernel" \
+	|| printf '%s\n' "$line"
+done < "$BOOTCFG" > "$T"
 
 # Update file only if necessary.
-if ! cmp -s "$BOOTCFG" "$T"
+if ! cmp -s -- "$BOOTCFG" "$T"
 then
-	cat "$T" > "$BOOTCFG"
+	cat < "$T" > "$BOOTCFG"
 fi
